name: Deploy ASP.NET Core API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish -c Release -o /var/www/myapi/publish
      
    - name: Stop application
      run: sudo systemctl stop myapi.service || true
      
    - name: Copy files
      run: |
        sudo rm -rf /var/www/myapi/app
        sudo mv /var/www/myapi/publish /var/www/myapi/app
        sudo chown -R github-runner:github-runner /var/www/myapi/app
        
    - name: Start application
      run: |
        sudo systemctl start myapi.service
        sudo systemctl status myapi.service
