# Production docker-compose
# Используйте переменные окружения REGISTRY и IMAGE_TAG для подстановки реестра и тега образов.
# Пример запуска на сервере перед деплоем:
# export REGISTRY=myregistry.example.com/loftback
# export IMAGE_TAG=v2025.10.09
# docker compose -f docker-compose.yml pull
# docker compose -f docker-compose.yml up -d

networks:
  loftnet:
    driver: bridge

services:
  # =============================
  # API Gateway (Ocelot)
  # =============================
  apigateway:
    image: "${REGISTRY:-loftback}/apigateway:${IMAGE_TAG:-latest}"
    build:
      context: ../../src/ApiGateway
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:8080"  # Доступ к Gateway с хоста
    restart: unless-stopped
    depends_on:
      - cartservice
      - orderservice
      - productservice
      - userservice
      - paymentservice
      - shippingaddressservice
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - loftnet

  # =============================
  # Cart Service
  # =============================
  cartservice:
    image: "${REGISTRY:-loftback}/cartservice:${IMAGE_TAG:-latest}"
    build:
      context: ../../src/CartService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "8080" # внутри сети
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - loftnet

  # =============================
  # Order Service
  # =============================
  orderservice:
    image: "${REGISTRY:-loftback}/orderservice:${IMAGE_TAG:-latest}"
    build:
      context: ../../src/OrderService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - loftnet

  # =============================
  # Payment Service
  # =============================
  paymentservice:
    image: "${REGISTRY:-loftback}/paymentservice:${IMAGE_TAG:-latest}"
    build:
      context: ../../src/PaymentService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - loftnet

  # =============================
  # Product Service
  # =============================
  productservice:
    image: "${REGISTRY:-loftback}/productservice:${IMAGE_TAG:-latest}"
    build:
      context: ../../src/ProductService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - loftnet

  # =============================
  # Shipping Address Service
  # =============================
  shippingaddressservice:
    image: "${REGISTRY:-loftback}/shippingaddressservice:${IMAGE_TAG:-latest}"
    build:
      context: ../../src/ShippingAddressService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - loftnet

  # =============================
  # User Service
  # =============================
  userservice:
    image: "${REGISTRY:-loftback}/userservice:${IMAGE_TAG:-latest}"
    build:
      context: ../../src/UserService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - loftnet

  web-proxy:
    image: nginx:alpine
    container_name: web-proxy-nginx
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - "/home/dev/Test-LofBack/nginx/config:/etc/nginx/conf.d"
    restart: unless-stopped
    depends_on:
      - cartservice
      - orderservice
      - productservice
      - userservice
      - apigateway
      - paymentservice
      - shippingaddressservice
    networks:
      - loftnet
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
